# generated by datamodel-codegen:
#   filename:  annotations.json
#   timestamp: 2022-08-24T11:58:18+00:00

from __future__ import annotations

from typing import Any, List, Optional, Union

from pydantic import BaseModel


class Segment(BaseModel):
    id: str
    start: str
    stop: str
    url: str


class Segments(BaseModel):
    segment: Segment


class Owner(BaseModel):
    username: str
    email: str


class LabelItem(BaseModel):
    name: str
    color: str
    type: str
    attributes: Any


class Labels(BaseModel):
    label: List[LabelItem]


class Task(BaseModel):
    id: str
    name: str
    size: str
    mode: str
    overlap: str
    bugtracker: Any
    created: str
    updated: str
    subset: str
    start_frame: str
    stop_frame: str
    frame_filter: Any
    segments: Segments
    owner: Owner
    assignee: Any
    labels: Labels


class Meta(BaseModel):
    task: Task
    dumped: str


class Point(BaseModel):
    _label: str
    _occluded: str
    _source: str
    _points: str
    _z_order: str
    _group_id: Optional[str] = None


class Point1(BaseModel):
    _label: str
    _occluded: str
    _source: str
    _points: str
    _z_order: str


class ImageItem(BaseModel):
    _id: str
    _name: str
    _width: str
    _height: str
    points: Optional[Union[List[Point], Point1]] = None


class Annotations(BaseModel):
    version: str
    meta: Meta
    image: List[ImageItem]


class CVATKeypointsParser(BaseModel):
    annotations: Annotations
