# generated by datamodel-codegen:
#   filename:  annotations.json
#   timestamp: 2022-08-24T12:15:52+00:00
# then further changed by @tlips

from __future__ import annotations

from typing import Any, List, Optional, Union

from pydantic import BaseModel


class Segment(BaseModel):
    id: str
    start: str
    stop: str
    url: str


class Segments(BaseModel):
    segment: Segment


class Owner(BaseModel):
    username: str
    email: str


class LabelItem(BaseModel):
    name: str
    color: str
    type: str
    attributes: Any


class Labels(BaseModel):
    label: List[LabelItem]


class Task(BaseModel):
    id: str
    name: str
    size: str
    mode: str
    overlap: str
    bugtracker: Any
    created: str
    updated: str
    subset: str
    start_frame: str
    stop_frame: str
    frame_filter: Any
    segments: Segments
    owner: Owner
    assignee: Any
    labels: Labels


class Meta(BaseModel):
    task: Task
    dumped: str


class Point(BaseModel):
    label: str
    occluded: str
    source: str
    points: str
    z_order: str
    group_id: Optional[str] = "1" # set default group id to 1.


class ImageItem(BaseModel):
    id: str
    name: str
    width: str
    height: str
    points: Optional[Union[List[Point], Point]] = None


class Annotations(BaseModel):
    version: str
    meta: Meta
    image: List[ImageItem]


class CVATKeypointsParser(BaseModel):
    annotations: Annotations
